-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "coupon" TEXT,
ADD COLUMN     "discount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fakeuser" INTEGER NOT NULL DEFAULT 348,
ADD COLUMN     "price" INTEGER NOT NULL DEFAULT 0;
